management:
  security:
    enabled: false

security:
  basic:
    enabled: false

endpoints:
 shutdown:
  enabled: true

zuul:
  host:
    connect-timeout-millis: 50000
    socket-timeout-millis: 500000

  ribbon:
    ConnectionTimeout: 50000
    ReadTimeout: 50000
    MaxAutoRetries: 0
